### DISCUSSION TITLE
Statically-linked Windows Builds

### DISCUSSION THREAD

**Discussion by seangibbz** [86Box/86Box#4598] [Ideas]
To automate the downloading / installation / updating of 86Box, Windows users [may wish to utilize](https://github.com/microsoft/winget-pkgs/issues/111311) the [winget package manager](https://github.com/microsoft/winget-cli/).

While it is currently possible to create a winget manifest for both `zip` and `portable` installations (for which the current releases of 86Box would be classified as a combination), [winget does not support portable exe's that rely on dynamically-linked libraries](https://github.com/microsoft/winget-cli/issues/2711) (i.e. DLL files) due to winget creating a symlink for portable installs when adding to the Windows PATH environment variable.

A statically-linked portable executable release would eliminate this problem and could offer users an easy way of package/version-management (via winget) [without the need to create full Windows Installer Packages](https://github.com/86Box/86Box/discussions/4596) for each release.

**Comment by seangibbz** [comment]
Example winget [manifest](https://github.com/microsoft/winget-pkgs) (for 86Box v4.1.1):

`86Box.86Box.yaml`
```yaml
PackageIdentifier: 86Box.86Box
PackageVersion: 4.1.1
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
```
`86Box.86Box.locale.en-US.yaml`
```yaml
PackageIdentifier: 86Box.86Box
PackageVersion: 4.1.1
PackageLocale: en-US
Publisher: 86Box Project
PublisherUrl: https://86box.net
PublisherSupportUrl: https://paypal.me/86Box
PackageName: 86Box
License: GNU General Public License v2.0
LicenseUrl: https://github.com/86Box/86Box/blob/master/COPYING
ShortDescription: Emulator of retro x86-based machines
Description: 86Box is a low level x86 emulator that runs older operating systems and software designed for IBM PC systems and compatibles from 1981 through fairly recent system designs based on the PCI bus.
Moniker: 86box
Tags:
- 86box
- emulator
- ibm
- pc
- pcem
- x86
Documentations:
  - DocumentLabel: Documentation
    DocumentUrl: https://86box.readthedocs.io/en/latest/index.html
ReleaseNotes: This is the March 2024 update to 86Box, bringing bugfixes over the original v4.1 release and some new hardware.
ReleaseNotesUrl: https://86box.net/2024/03/20/86box-v4-1-1.html
ManifestType: defaultLocale
ManifestVersion: 1.6.0
```
`86Box.86Box.installer.yaml`
```yaml
PackageIdentifier: 86Box.86Box
PackageVersion: 4.1.1
# Channel: stable
InstallerType: zip
ReleaseDate: 2024-03-20
Installers:
- Architecture: x64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: 86Box.exe
    PortableCommandAlias: 86Box
  InstallerUrl: https://github.com/86Box/86Box/releases/download/v4.1.1/86Box-Windows-64-b5634.zip
  InstallerSha256: 2860B40A12ED2EB25241D0C653FA108465947600D0240C7C32783163A2515CD3
- Architecture: x86
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: 86Box.exe
    PortableCommandAlias: 86Box
  InstallerUrl: https://github.com/86Box/86Box/releases/download/v4.1.1/86Box-Windows-32-b5634.zip
  InstallerSha256: C97CFBA2B27185DD5F97C67BA530714A66C37E05B76047B10722130B8B0896E1
ManifestType: installer
ManifestVersion: 1.6.0
```
